// DO NOT EDIT. generated by webtyp.com/ormc

package devicemanager

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type Device struct {
	Id string
	TenantId string
	Name string
	Type string
	Location string
	ZoneId string
	Access string
	IsActive bool
	UpdatedAt int64
}

func (m *Device) ModelName() string { return "device" }

func (m *Device) Schema() []model.Field { return DeviceModel.Fields }

func (m *Device) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.Name, &m.Type, &m.Location, &m.ZoneId, &m.Access, &m.IsActive, &m.UpdatedAt} }

func (m *Device) IsNil() bool { return m == nil }

func (m *Device) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("name", m.Name)
	w.String("type", m.Type)
	if m.Location != "" { w.String("location", m.Location) }
	if m.ZoneId != "" { w.String("zone_id", m.ZoneId) }
	w.String("access", m.Access)
	w.Bool("is_active", m.IsActive)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *Device) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.String("location"); ok { m.Location = v }
	if v, ok := r.String("zone_id"); ok { m.ZoneId = v }
	if v, ok := r.String("access"); ok { m.Access = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type DeviceList []*Device

func (s *DeviceList) Len() int             { return len(*s) }
func (s *DeviceList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeviceList) Append() model.Fielder  { v := &Device{}; *s = append(*s, v); return v }
func (s *DeviceList) IsNil() bool          { return s == nil }
func (s *DeviceList) EncodeFields(_ model.FieldWriter) {}
func (s *DeviceList) DecodeFields(_ model.FieldReader) {}

func (m *Device) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Device_ = struct {
	Id string
	TenantId string
	Name string
	Type string
	Location string
	ZoneId string
	Access string
	IsActive string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	Name: "name",
	Type: "type",
	Location: "location",
	ZoneId: "zone_id",
	Access: "access",
	IsActive: "is_active",
	UpdatedAt: "updated_at",
}

func ReadOneDevice(qb *orm.QB, model *Device) (*Device, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllDevice(qb *orm.QB) (DeviceList, error) {
	var results DeviceList
	err := qb.ReadAll(
		func() model.Model { return &Device{} },
		func(m model.Model) { results = append(results, m.(*Device)) },
	)
	return results, err
}

type Zone struct {
	Id string
	TenantId string
	Name string
	RangeStart string
	RangeEnd string
	UpdatedAt int64
}

func (m *Zone) ModelName() string { return "zone" }

func (m *Zone) Schema() []model.Field { return ZoneModel.Fields }

func (m *Zone) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.Name, &m.RangeStart, &m.RangeEnd, &m.UpdatedAt} }

func (m *Zone) IsNil() bool { return m == nil }

func (m *Zone) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("name", m.Name)
	w.String("range_start", m.RangeStart)
	w.String("range_end", m.RangeEnd)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *Zone) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("range_start"); ok { m.RangeStart = v }
	if v, ok := r.String("range_end"); ok { m.RangeEnd = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type ZoneList []*Zone

func (s *ZoneList) Len() int             { return len(*s) }
func (s *ZoneList) At(i int) model.Fielder { return (*s)[i] }
func (s *ZoneList) Append() model.Fielder  { v := &Zone{}; *s = append(*s, v); return v }
func (s *ZoneList) IsNil() bool          { return s == nil }
func (s *ZoneList) EncodeFields(_ model.FieldWriter) {}
func (s *ZoneList) DecodeFields(_ model.FieldReader) {}

func (m *Zone) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Zone_ = struct {
	Id string
	TenantId string
	Name string
	RangeStart string
	RangeEnd string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	Name: "name",
	RangeStart: "range_start",
	RangeEnd: "range_end",
	UpdatedAt: "updated_at",
}

func ReadOneZone(qb *orm.QB, model *Zone) (*Zone, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllZone(qb *orm.QB) (ZoneList, error) {
	var results ZoneList
	err := qb.ReadAll(
		func() model.Model { return &Zone{} },
		func(m model.Model) { results = append(results, m.(*Zone)) },
	)
	return results, err
}

type NetworkInterface struct {
	Id string
	TenantId string
	DeviceId string
	Label string
	Mac string
	Ip string
	UpdatedAt int64
}

func (m *NetworkInterface) ModelName() string { return "network_interface" }

func (m *NetworkInterface) Schema() []model.Field { return NetworkInterfaceModel.Fields }

func (m *NetworkInterface) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.DeviceId, &m.Label, &m.Mac, &m.Ip, &m.UpdatedAt} }

func (m *NetworkInterface) IsNil() bool { return m == nil }

func (m *NetworkInterface) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("device_id", m.DeviceId)
	w.String("label", m.Label)
	if m.Mac != "" { w.String("mac", m.Mac) }
	if m.Ip != "" { w.String("ip", m.Ip) }
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *NetworkInterface) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("device_id"); ok { m.DeviceId = v }
	if v, ok := r.String("label"); ok { m.Label = v }
	if v, ok := r.String("mac"); ok { m.Mac = v }
	if v, ok := r.String("ip"); ok { m.Ip = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type NetworkInterfaceList []*NetworkInterface

func (s *NetworkInterfaceList) Len() int             { return len(*s) }
func (s *NetworkInterfaceList) At(i int) model.Fielder { return (*s)[i] }
func (s *NetworkInterfaceList) Append() model.Fielder  { v := &NetworkInterface{}; *s = append(*s, v); return v }
func (s *NetworkInterfaceList) IsNil() bool          { return s == nil }
func (s *NetworkInterfaceList) EncodeFields(_ model.FieldWriter) {}
func (s *NetworkInterfaceList) DecodeFields(_ model.FieldReader) {}

func (m *NetworkInterface) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var NetworkInterface_ = struct {
	Id string
	TenantId string
	DeviceId string
	Label string
	Mac string
	Ip string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	DeviceId: "device_id",
	Label: "label",
	Mac: "mac",
	Ip: "ip",
	UpdatedAt: "updated_at",
}

func ReadOneNetworkInterface(qb *orm.QB, model *NetworkInterface) (*NetworkInterface, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllNetworkInterface(qb *orm.QB) (NetworkInterfaceList, error) {
	var results NetworkInterfaceList
	err := qb.ReadAll(
		func() model.Model { return &NetworkInterface{} },
		func(m model.Model) { results = append(results, m.(*NetworkInterface)) },
	)
	return results, err
}

func (m *NetworkInterface) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: NetworkInterfaceModel.Fields[2], Ref: "device", RefColumn: "id", OnDelete: ""},
	}
}

type ListDevicesArgs struct {
	TenantId string
	Type string
	ActiveOnly bool
	Limit int64
	Offset int64
}

func (m *ListDevicesArgs) ModelName() string { return "list_devices_args" }

func (m *ListDevicesArgs) Schema() []model.Field { return ListDevicesArgsModel.Fields }

func (m *ListDevicesArgs) Pointers() []any { return []any{&m.TenantId, &m.Type, &m.ActiveOnly, &m.Limit, &m.Offset} }

func (m *ListDevicesArgs) IsNil() bool { return m == nil }

func (m *ListDevicesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("type", m.Type)
	w.Bool("active_only", m.ActiveOnly)
	w.Int("limit", m.Limit)
	w.Int("offset", m.Offset)
}

func (m *ListDevicesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("type"); ok { m.Type = v }
	if v, ok := r.Bool("active_only"); ok { m.ActiveOnly = v }
	if v, ok := r.Int("limit"); ok { m.Limit = v }
	if v, ok := r.Int("offset"); ok { m.Offset = v }
}

type ListDevicesArgsList []*ListDevicesArgs

func (s *ListDevicesArgsList) Len() int             { return len(*s) }
func (s *ListDevicesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListDevicesArgsList) Append() model.Fielder  { v := &ListDevicesArgs{}; *s = append(*s, v); return v }
func (s *ListDevicesArgsList) IsNil() bool          { return s == nil }
func (s *ListDevicesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListDevicesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListDevicesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetDeviceArgs struct {
	TenantId string
	Id string
}

func (m *GetDeviceArgs) ModelName() string { return "get_device_args" }

func (m *GetDeviceArgs) Schema() []model.Field { return GetDeviceArgsModel.Fields }

func (m *GetDeviceArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *GetDeviceArgs) IsNil() bool { return m == nil }

func (m *GetDeviceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *GetDeviceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type GetDeviceArgsList []*GetDeviceArgs

func (s *GetDeviceArgsList) Len() int             { return len(*s) }
func (s *GetDeviceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetDeviceArgsList) Append() model.Fielder  { v := &GetDeviceArgs{}; *s = append(*s, v); return v }
func (s *GetDeviceArgsList) IsNil() bool          { return s == nil }
func (s *GetDeviceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetDeviceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetDeviceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeactivateDeviceArgs struct {
	TenantId string
	Id string
}

func (m *DeactivateDeviceArgs) ModelName() string { return "deactivate_device_args" }

func (m *DeactivateDeviceArgs) Schema() []model.Field { return DeactivateDeviceArgsModel.Fields }

func (m *DeactivateDeviceArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeactivateDeviceArgs) IsNil() bool { return m == nil }

func (m *DeactivateDeviceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeactivateDeviceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeactivateDeviceArgsList []*DeactivateDeviceArgs

func (s *DeactivateDeviceArgsList) Len() int             { return len(*s) }
func (s *DeactivateDeviceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeactivateDeviceArgsList) Append() model.Fielder  { v := &DeactivateDeviceArgs{}; *s = append(*s, v); return v }
func (s *DeactivateDeviceArgsList) IsNil() bool          { return s == nil }
func (s *DeactivateDeviceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeactivateDeviceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeactivateDeviceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeleteDeviceArgs struct {
	TenantId string
	Id string
}

func (m *DeleteDeviceArgs) ModelName() string { return "delete_device_args" }

func (m *DeleteDeviceArgs) Schema() []model.Field { return DeleteDeviceArgsModel.Fields }

func (m *DeleteDeviceArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteDeviceArgs) IsNil() bool { return m == nil }

func (m *DeleteDeviceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteDeviceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteDeviceArgsList []*DeleteDeviceArgs

func (s *DeleteDeviceArgsList) Len() int             { return len(*s) }
func (s *DeleteDeviceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteDeviceArgsList) Append() model.Fielder  { v := &DeleteDeviceArgs{}; *s = append(*s, v); return v }
func (s *DeleteDeviceArgsList) IsNil() bool          { return s == nil }
func (s *DeleteDeviceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteDeviceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeleteDeviceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListZonesArgs struct {
	TenantId string
}

func (m *ListZonesArgs) ModelName() string { return "list_zones_args" }

func (m *ListZonesArgs) Schema() []model.Field { return ListZonesArgsModel.Fields }

func (m *ListZonesArgs) Pointers() []any { return []any{&m.TenantId} }

func (m *ListZonesArgs) IsNil() bool { return m == nil }

func (m *ListZonesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
}

func (m *ListZonesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
}

type ListZonesArgsList []*ListZonesArgs

func (s *ListZonesArgsList) Len() int             { return len(*s) }
func (s *ListZonesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListZonesArgsList) Append() model.Fielder  { v := &ListZonesArgs{}; *s = append(*s, v); return v }
func (s *ListZonesArgsList) IsNil() bool          { return s == nil }
func (s *ListZonesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListZonesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListZonesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeleteZoneArgs struct {
	TenantId string
	Id string
}

func (m *DeleteZoneArgs) ModelName() string { return "delete_zone_args" }

func (m *DeleteZoneArgs) Schema() []model.Field { return DeleteZoneArgsModel.Fields }

func (m *DeleteZoneArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteZoneArgs) IsNil() bool { return m == nil }

func (m *DeleteZoneArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteZoneArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteZoneArgsList []*DeleteZoneArgs

func (s *DeleteZoneArgsList) Len() int             { return len(*s) }
func (s *DeleteZoneArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteZoneArgsList) Append() model.Fielder  { v := &DeleteZoneArgs{}; *s = append(*s, v); return v }
func (s *DeleteZoneArgsList) IsNil() bool          { return s == nil }
func (s *DeleteZoneArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteZoneArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeleteZoneArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListNetworkInterfacesArgs struct {
	TenantId string
	DeviceId string
}

func (m *ListNetworkInterfacesArgs) ModelName() string { return "list_network_interfaces_args" }

func (m *ListNetworkInterfacesArgs) Schema() []model.Field { return ListNetworkInterfacesArgsModel.Fields }

func (m *ListNetworkInterfacesArgs) Pointers() []any { return []any{&m.TenantId, &m.DeviceId} }

func (m *ListNetworkInterfacesArgs) IsNil() bool { return m == nil }

func (m *ListNetworkInterfacesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("device_id", m.DeviceId)
}

func (m *ListNetworkInterfacesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("device_id"); ok { m.DeviceId = v }
}

type ListNetworkInterfacesArgsList []*ListNetworkInterfacesArgs

func (s *ListNetworkInterfacesArgsList) Len() int             { return len(*s) }
func (s *ListNetworkInterfacesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListNetworkInterfacesArgsList) Append() model.Fielder  { v := &ListNetworkInterfacesArgs{}; *s = append(*s, v); return v }
func (s *ListNetworkInterfacesArgsList) IsNil() bool          { return s == nil }
func (s *ListNetworkInterfacesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListNetworkInterfacesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListNetworkInterfacesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeleteNetworkInterfaceArgs struct {
	TenantId string
	Id string
}

func (m *DeleteNetworkInterfaceArgs) ModelName() string { return "delete_network_interface_args" }

func (m *DeleteNetworkInterfaceArgs) Schema() []model.Field { return DeleteNetworkInterfaceArgsModel.Fields }

func (m *DeleteNetworkInterfaceArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteNetworkInterfaceArgs) IsNil() bool { return m == nil }

func (m *DeleteNetworkInterfaceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteNetworkInterfaceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeleteNetworkInterfaceArgsList []*DeleteNetworkInterfaceArgs

func (s *DeleteNetworkInterfaceArgsList) Len() int             { return len(*s) }
func (s *DeleteNetworkInterfaceArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteNetworkInterfaceArgsList) Append() model.Fielder  { v := &DeleteNetworkInterfaceArgs{}; *s = append(*s, v); return v }
func (s *DeleteNetworkInterfaceArgsList) IsNil() bool          { return s == nil }
func (s *DeleteNetworkInterfaceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteNetworkInterfaceArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeleteNetworkInterfaceArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

