// DO NOT EDIT. generated by github.com/tinywasm/orm

package devicemanager

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type Device struct {
	Id        string
	TenantId  string
	Name      string
	Ip        string
	Type      string
	Location  string
	IsActive  bool
	UpdatedAt int64
}

func (m *Device) ModelName() string { return "device" }

func (m *Device) Schema() []model.Field { return DeviceModel.Fields }

func (m *Device) Pointers() []any {
	return []any{&m.Id, &m.TenantId, &m.Name, &m.Ip, &m.Type, &m.Location, &m.IsActive, &m.UpdatedAt}
}

func (m *Device) IsNil() bool { return m == nil }

func (m *Device) EncodeFields(w model.FieldWriter) {
	if m.Id != "" {
		w.String("id", m.Id)
	}
	w.String("tenant_id", m.TenantId)
	w.String("name", m.Name)
	w.String("ip", m.Ip)
	w.String("type", m.Type)
	if m.Location != "" {
		w.String("location", m.Location)
	}
	w.Bool("is_active", m.IsActive)
	if m.UpdatedAt != 0 {
		w.Int("updated_at", m.UpdatedAt)
	}
}

func (m *Device) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("name"); ok {
		m.Name = v
	}
	if v, ok := r.String("ip"); ok {
		m.Ip = v
	}
	if v, ok := r.String("type"); ok {
		m.Type = v
	}
	if v, ok := r.String("location"); ok {
		m.Location = v
	}
	if v, ok := r.Bool("is_active"); ok {
		m.IsActive = v
	}
	if v, ok := r.Int("updated_at"); ok {
		m.UpdatedAt = v
	}
}

type DeviceList []*Device

func (s *DeviceList) Schema() []model.Field { return nil }
func (s *DeviceList) Pointers() []any       { return nil }
func (s *DeviceList) Len() int              { return len(*s) }
func (s *DeviceList) At(i int) model.Fielder {
	return (*s)[i]
}
func (s *DeviceList) Append() model.Fielder {
	v := &Device{}
	*s = append(*s, v)
	return v
}
func (s *DeviceList) IsNil() bool                      { return s == nil }
func (s *DeviceList) EncodeFields(_ model.FieldWriter) {}
func (s *DeviceList) DecodeFields(_ model.FieldReader) {}

func (m *Device) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Device_ = struct {
	Id        string
	TenantId  string
	Name      string
	Ip        string
	Type      string
	Location  string
	IsActive  string
	UpdatedAt string
}{
	Id:        "id",
	TenantId:  "tenant_id",
	Name:      "name",
	Ip:        "ip",
	Type:      "type",
	Location:  "location",
	IsActive:  "is_active",
	UpdatedAt: "updated_at",
}

func ReadOneDevice(qb *orm.QB, model *Device) (*Device, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllDevice(qb *orm.QB) (DeviceList, error) {
	var results DeviceList
	err := qb.ReadAll(
		func() model.Model { return &Device{} },
		func(m model.Model) { results = append(results, m.(*Device)) },
	)
	return results, err
}

type ListDevicesArgs struct {
	TenantId   string
	Type       string
	ActiveOnly bool
	Limit      int64
	Offset     int64
}

func (m *ListDevicesArgs) ModelName() string { return "list_devices_args" }

func (m *ListDevicesArgs) Schema() []model.Field { return ListDevicesArgsModel.Fields }

func (m *ListDevicesArgs) Pointers() []any {
	return []any{&m.TenantId, &m.Type, &m.ActiveOnly, &m.Limit, &m.Offset}
}

func (m *ListDevicesArgs) IsNil() bool { return m == nil }

func (m *ListDevicesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("type", m.Type)
	w.Bool("active_only", m.ActiveOnly)
	w.Int("limit", m.Limit)
	w.Int("offset", m.Offset)
}

func (m *ListDevicesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("type"); ok {
		m.Type = v
	}
	if v, ok := r.Bool("active_only"); ok {
		m.ActiveOnly = v
	}
	if v, ok := r.Int("limit"); ok {
		m.Limit = v
	}
	if v, ok := r.Int("offset"); ok {
		m.Offset = v
	}
}

type ListDevicesArgsList []*ListDevicesArgs

func (s *ListDevicesArgsList) Schema() []model.Field { return nil }
func (s *ListDevicesArgsList) Pointers() []any       { return nil }
func (s *ListDevicesArgsList) Len() int              { return len(*s) }
func (s *ListDevicesArgsList) At(i int) model.Fielder {
	return (*s)[i]
}
func (s *ListDevicesArgsList) Append() model.Fielder {
	v := &ListDevicesArgs{}
	*s = append(*s, v)
	return v
}
func (s *ListDevicesArgsList) IsNil() bool                      { return s == nil }
func (s *ListDevicesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListDevicesArgsList) DecodeFields(_ model.FieldReader) {}

type GetDeviceArgs struct {
	TenantId string
	Id       string
}

func (m *GetDeviceArgs) ModelName() string { return "get_device_args" }

func (m *GetDeviceArgs) Schema() []model.Field { return GetDeviceArgsModel.Fields }

func (m *GetDeviceArgs) Pointers() []any {
	return []any{&m.TenantId, &m.Id}
}

func (m *GetDeviceArgs) IsNil() bool { return m == nil }

func (m *GetDeviceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *GetDeviceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
}

type GetDeviceArgsList []*GetDeviceArgs

func (s *GetDeviceArgsList) Schema() []model.Field { return nil }
func (s *GetDeviceArgsList) Pointers() []any       { return nil }
func (s *GetDeviceArgsList) Len() int              { return len(*s) }
func (s *GetDeviceArgsList) At(i int) model.Fielder {
	return (*s)[i]
}
func (s *GetDeviceArgsList) Append() model.Fielder {
	v := &GetDeviceArgs{}
	*s = append(*s, v)
	return v
}
func (s *GetDeviceArgsList) IsNil() bool                      { return s == nil }
func (s *GetDeviceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetDeviceArgsList) DecodeFields(_ model.FieldReader) {}

type DeactivateDeviceArgs struct {
	TenantId string
	Id       string
}

func (m *DeactivateDeviceArgs) ModelName() string { return "deactivate_device_args" }

func (m *DeactivateDeviceArgs) Schema() []model.Field { return DeactivateDeviceArgsModel.Fields }

func (m *DeactivateDeviceArgs) Pointers() []any {
	return []any{&m.TenantId, &m.Id}
}

func (m *DeactivateDeviceArgs) IsNil() bool { return m == nil }

func (m *DeactivateDeviceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeactivateDeviceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
}

type DeactivateDeviceArgsList []*DeactivateDeviceArgs

func (s *DeactivateDeviceArgsList) Schema() []model.Field { return nil }
func (s *DeactivateDeviceArgsList) Pointers() []any       { return nil }
func (s *DeactivateDeviceArgsList) Len() int              { return len(*s) }
func (s *DeactivateDeviceArgsList) At(i int) model.Fielder {
	return (*s)[i]
}
func (s *DeactivateDeviceArgsList) Append() model.Fielder {
	v := &DeactivateDeviceArgs{}
	*s = append(*s, v)
	return v
}
func (s *DeactivateDeviceArgsList) IsNil() bool                      { return s == nil }
func (s *DeactivateDeviceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeactivateDeviceArgsList) DecodeFields(_ model.FieldReader) {}

type DeleteDeviceArgs struct {
	TenantId string
	Id       string
}

func (m *DeleteDeviceArgs) ModelName() string { return "delete_device_args" }

func (m *DeleteDeviceArgs) Schema() []model.Field { return DeleteDeviceArgsModel.Fields }

func (m *DeleteDeviceArgs) Pointers() []any {
	return []any{&m.TenantId, &m.Id}
}

func (m *DeleteDeviceArgs) IsNil() bool { return m == nil }

func (m *DeleteDeviceArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteDeviceArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
}

type DeleteDeviceArgsList []*DeleteDeviceArgs

func (s *DeleteDeviceArgsList) Schema() []model.Field { return nil }
func (s *DeleteDeviceArgsList) Pointers() []any       { return nil }
func (s *DeleteDeviceArgsList) Len() int              { return len(*s) }
func (s *DeleteDeviceArgsList) At(i int) model.Fielder {
	return (*s)[i]
}
func (s *DeleteDeviceArgsList) Append() model.Fielder {
	v := &DeleteDeviceArgs{}
	*s = append(*s, v)
	return v
}
func (s *DeleteDeviceArgsList) IsNil() bool                      { return s == nil }
func (s *DeleteDeviceArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteDeviceArgsList) DecodeFields(_ model.FieldReader) {}
